### ISSUE TITLE
Payment.fns.restrictNumeric is not a function- should it be Payment.restrictNumeric?

### ISSUE THREAD

**Issue by steveTripactions** [jessepollak/payment#93]
Removed the .fns and it seemed to work on v1.0.9
